### ISSUE TITLE
HFM 9.28.1718 timeout on some client

### ISSUE THREAD

**Issue by Adanorm** [harlam357/hfm-net#355]
Hello Harlam, I just updated my HFM.net to 9.28.1718 (and installed new .net Framework).

2 of my 6 clients now reports "timeouts".

Just before the update all was OK.
[15/01/2022-19:46:18] X (Serveur 4) Connection attempt has timed out.
[15/01/2022-19:46:18] X System.TimeoutException: Connection attempt has timed out.
   at HFM.Client.Sockets.TcpClientConnection.ConnectAsync(String host, Int32 port, Int32 timeout)
   at HFM.Client.FahClientConnection.OpenAsync()
   at HFM.Core.Client.FahClient.CreateAndOpenConnection()
   at HFM.Core.Client.FahClient.OnConnect()
   at HFM.Core.Client.Client.Connect()
   at HFM.Core.Client.Client.Retrieve()
[15/01/2022-19:46:18] X (Poste 11) Connection attempt has timed out.
[15/01/2022-19:46:18] X System.TimeoutException: Connection attempt has timed out.
   at HFM.Client.Sockets.TcpClientConnection.ConnectAsync(String host, Int32 port, Int32 timeout)
   at HFM.Client.FahClientConnection.OpenAsync()
   at HFM.Core.Client.FahClient.CreateAndOpenConnection()
   at HFM.Core.Client.FahClient.OnConnect()
   at HFM.Core.Client.Client.Connect()
   at HFM.Core.Client.Client.Retrieve()

Serveur 4 is a PC running Ubuntu 20.04 and Fah 7.6.21.
Poste 11 is a PC running Windows 10 and Fah 7.6.21.

HFM is installed on a Windows 11 PC. 

Thank you in advance

**Comment by Adanorm** [comment]
The rollback to the previous version fixes temporarily the issue

**Comment by Adanorm** [comment]
[07/02/2022-11:33:52] X (Poste 11) Unable to read data from the transport connection: L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application..
[07/02/2022-11:33:52] X System.IO.IOException: Unable to read data from the transport connection: L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application..
 ---> System.Net.Sockets.SocketException (995): L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at HFM.Client.FahClientReader.OnReadStreamAsync(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at HFM.Client.FahClientReader.ReadAsync()
   at HFM.Core.Client.FahClient.ReadMessagesFromConnection()
[07/02/2022-11:33:52] X The process cannot access the file 'E:\Seafile\Folding@Home\rennes.hfmx' because it is being used by another process.
[07/02/2022-11:33:52] X System.IO.IOException: The process cannot access the file 'E:\Seafile\Folding@Home\rennes.hfmx' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at HFM.Core.Client.ClientSettingsFileSerializer.Serialize(String path, List`1 value)
   at HFM.Forms.ClientSettingsManager.Write(IEnumerable`1 settings, String path, Int32 filterIndex)
   at HFM.Forms.Presenters.MainPresenter.WriteClientConfiguration(String fileName, Int32 filterIndex)

**Comment by Adanorm** [comment]
Confirmed local DNS lookup has error when using IPv4/IPv6

**Comment by harlam357** [comment]
Closing. Issue not related to HFM.
