### ISSUE TITLE
I can't figure out why I see p19432 like this?

### ISSUE THREAD

**Issue by artoar11** [harlam357/hfm-net#366]
This is the first time this has happened to me. Restarted HFM, same thing:

Application: HFM v10.1.1994
OS Version: Microsoft Windows NT 10.0.19045.0
Exception Thrown:
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at HFM.Forms.Models.ProjectComparisonZedGraphBenchmarksReport.<>c.<Generate>b__5_4(ValueTuple`2 x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at HFM.Forms.Models.ProjectComparisonZedGraphBenchmarksReport.Generate(IBenchmarksReportSource source)
   at HFM.Forms.Models.BenchmarksModel.RunReports()
   at HFM.Forms.Models.BenchmarksModel.OnSelectedSlotProjectListItemsChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
![p19432](https://user-images.githubusercontent.com/130217952/232451552-86f67207-ada5-42f8-a196-c2dd5e9021b0.png)

**Comment by harlam357** [comment]
@artoar11, I have fixed the reported exception based on the given stack trace. However, I don't know yet what to do about this p19432 project. I do not find it in the psummary json.

The other puzzling part of the equation is there is a guard in the code to defend against capturing a work unit with no Project Number (ID).

Will reach out on Slack and get you to send me your database file so I can look at the details of what was written to the database. Then, I can write some cleanup code to purge the bad records from the database. Should also give me some clues where I can add more guards to avoid this situation in the future.

**Comment by harlam357** [comment]
Marked as fixed for v10.2
